React capstone project - Metrics web app
AlselwiAisha/React-Capstone-App-m3 pull request #6
Opened 2023-10-11 17:00 UTC by AlselwiAisha

**Description:**
- Use React documentation.
- Use React components.
- Use React props.
- Use React Router.
- Connect React and Redux.
- Handle events in a React app.
- Write integration tests with a React testing library.
- Use styles in a React app.
- Use React life cycle methods.
- Apply React best practices and language style guides in code.
- Use store, actions and reducers in React.

- Select the API.
- Build files structure for my React app.
- Prepare routes and navigation in your app.
- User can display a list of items and filter them. Data come from the API.
- Could you create the tests for the application?
- Style my components to match the design provided.
- Deploy the project and test for final details.
- Record a video for my project.
- Create a good README.

2023-10-11 18:23 UTC, shahadat3669 requested changes
Hi @AlselwiAisha, 

Great job so far! 👏 You've done well, and you're almost there for the next project ⏭️, but there are a few issues 🐛 that you still need to work on.

<img  src="https://media2.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif" />


## Don't Worry 🙏

It's okay to have bugs in your code. 🆗 Please see this code review as an opportunity to learn practical coding skills and discover new tips that can improve your code quality 💯 and help you **get even better** 💼.

**I will guide you on how to address these areas down below 👇.**

## Video presentation
Great job on your project presentation video! You adhered to the time limit, keeping it within the 5-minute mark, which is commendable. Your use of professional and clear English was excellent, making it easy to understand the project's topic and purpose. 

Your demo of the project was comprehensive and effectively highlighted all the essential features. This gave a clear sense of how the project works, which is crucial for the audience's understanding. Your choice to discuss a piece of code you found interesting or were proud of was a nice touch, as it provides insight into your thought process and enthusiasm for the project.

Overall, you did a fantastic job creating a well-structured and engaging project presentation video. Keep up the excellent work, and continue refining your presentation skills!

## Highlights
✅ The live version working fine.
✅ The project contains a `Home` page and a `Detail` page
✅ Home page filter working fine.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

<table width="100%" align="center">
  <tr>
    <td colspan="4" align="center">
      <strong>Contact me: Shahadat Hossain</strong>
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://github.com/shahadata3669">
        <img src="https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="GitHub">
      </a>
    </td>
    <td align="center">
      <a href="https://www.linkedin.com/in/shahadat-cseng/">
        <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn">
      </a>
    </td>
    <td align="center">
      <a href="https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V">
        <img src="https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white" alt="Slack">
      </a>
    </td>
    <td align="center">
      <a href="mailto:shahadat3669@gmail.com?subject=Microverse%20Code%20Review">
        <img src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" alt="Email">
      </a>
    </td>
  </tr>
</table>

## ⚠️ WARNING ⚠️

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-11 18:23 UTC, shahadat3669 commented on src/components/Navigation.jsx
> +  </nav>
- [x] Great job on adding the right font family, but in comparison to the design, the title looks a bit too large. Please consider updating the font size to better match the design.

- [x] Currently, both the home page and the details page display the same title. However, as per the design, they should change based on the page. Please update your code to display the appropriate titles for each page.

- [x] In the design, to the right side of the title, there were two icons, but you've added only one icon. Kindly try to update your code to include the missing icon and better align with the design.

| Page | Your | Design |
| --- | --- | --- | 
|  Home   |  ![image](https://github.com/AlselwiAisha/React-Capstone-App-m3/assets/55840999/6e202db5-c15d-469b-b1fe-02cbc8000f4c)| ![image](https://github.com/AlselwiAisha/React-Capstone-App-m3/assets/55840999/43c173e6-a374-484e-b90f-84b3413b022e)|
|  Details |  ![image](https://github.com/AlselwiAisha/React-Capstone-App-m3/assets/55840999/6e202db5-c15d-469b-b1fe-02cbc8000f4c)| ![image](https://github.com/AlselwiAisha/React-Capstone-App-m3/assets/55840999/f4d420e9-1d3d-4c9b-8678-7128e80ce183)|

2023-10-11 18:23 UTC, shahadat3669 commented on src/components/HomePage.jsx
> +      </div>
- [x] Well done on successfully changing the image and text based on the filter. However, I recommend following the design more closely. Currently, the image occupies 2/3 of the parent width, while the text takes up 1/3. As per the project requirements, each should occupy half of the width. Please consider updating your code to align with the design, ensuring both the image and text have an equal width. 👍 

| Your | Design |
| --- | --- |
|  ![image](https://github.com/AlselwiAisha/React-Capstone-App-m3/assets/55840999/462e65bc-2dba-4657-bdee-3c3d3d3e14b7)| ![image](https://github.com/AlselwiAisha/React-Capstone-App-m3/assets/55840999/1adc0e1a-7674-4848-bbc4-7c297c3afd92)|

2023-10-11 18:23 UTC, shahadat3669 commented on src/components/Country.jsx
> +    </div>
- [x] Currently, you are displaying the country name and region. However, as per the design, you should also show some numeric values alongside the country. Please consider updating your code to meet the project requirements.
- [x] The title appears to have a larger font size than the design. Kindly reduce the size to match the design specifications.
- [x] Additionally, the text should be right-aligned, but it is currently left-aligned. Please adjust the alignment accordingly.
- [x] The `nth-5` and `nth-6` cards should have different colors. Please consider adding the correct colors to these cards.
- [x] You are currently using a `div` tag to showcase the cards. As a best practice, it's recommended to use the `article` tag. Please consider updating it for better semantic structure.

| Your | Design |
| --- | --- |
|  ![image](https://github.com/AlselwiAisha/React-Capstone-App-m3/assets/55840999/5ec34cd2-7594-46ff-aad5-9edb577f78f8)| ![image](https://github.com/AlselwiAisha/React-Capstone-App-m3/assets/55840999/b2a22997-05ec-4636-9d94-f89ce0131782)|

2023-10-11 18:23 UTC, shahadat3669 commented on src/components/CountryDetails.jsx
> +        </div>
- [x] You've included an image in the headline section, which is great. However, according to the design, there should also be text accompanying the image based on countries. Please consider following the design and updating your code to include the necessary text.

| Your | Design |
| --- | --- |
|  ![image](https://github.com/AlselwiAisha/React-Capstone-App-m3/assets/55840999/d14516b9-16cb-4d70-a59f-be75082158f5)| ![image](https://github.com/AlselwiAisha/React-Capstone-App-m3/assets/55840999/20b8fe78-cfd7-472a-a5ec-fe384faf6e3c)|

2023-10-11 18:23 UTC, shahadat3669 commented on src/components/CountryDetails.jsx
> +      </div>
- [ ] Great job showcasing the country details. However, the spacing and text alignment do not follow the design. Each value should be right-aligned. Additionally, the left and right spacing is too much compared to the design. Please consider updating your code to align with the design.

| Your | Design |
| --- | --- |
|  ![image](https://github.com/AlselwiAisha/React-Capstone-App-m3/assets/55840999/8eb0c0f7-54fc-4c25-b32c-bc1e68b6a85a)| ![image](https://github.com/AlselwiAisha/React-Capstone-App-m3/assets/55840999/3fd9e434-e4c0-408c-bfa1-cb8adee4951a)|

2023-10-12 07:02 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @AlselwiAisha,

✔️ Nice implementation of search functionality and design

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-12 07:10 UTC, merged